---
title: "Data Processing README"
author: "Christian Opperman, Melanie Zheng, and Paul Choi"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Introduction

This document describes our group's philosophy and methodology behind the data cleaning, imputation, and feature generation/feature engineering for use in our Kaggle machine learning project for the NYC Data Science Academy.

Overall, we implemented the following pipeline for our data processing:

1. Import raw data
2. Remove outliers in training data
3. Impute data:
    + Impute pseudo-missing values
    + Impute true-missing values
    + Re-engineer categorical features as necessary
4. Add new feature variables
5. Dummify categorical feature variables
6. Remove unnecessary feature variables

One important quality of the data that it's important to reconcile is that there were many more feature variables with missing values in the test dataset than there were in the training dataset. As a result, our group decided on a data processing pipeline that took a function-forward approach, so that the end result would be a single function that would correctly process either the training or the test dataset. Therefore, the below detailed explanation puts forth our philosophy on first types of variables (pseudo-missing, true-missing, categorical, etc.) and then on specific variables, rather than on an individual dataset.

### Outliers in Training Data 
An examination of the distribution of our feature space revealed that there were two clear outliers in the relation between 'SalePrice' and 'GrLivArea' (a representation of the overall living area of the house). While the overall relationional trend between these two variables is positive and linear, there were two observations with a living area greater than 4000 square feet but a sale price less than $300,000, which had negative effects on the overall trend between the two variables.

Because there were only two observations out of the 1,460 observations in our training data, we judged it more efficient to remove those observations than to attempt to transform the 'GrLivArea' variable to reduce the outlier-induced skew.

### Data Imputation
#### Pseudo-Missing Values
There were a number of feature variables that contained missing values that did not, in fact, represent missing data. Instead of an incomplete observation, missing values in these features represented a lack of the element in question on the property. Our group termed those features with this quality "pseudo-missing."

The general philosophy for a given variable X (where X represents a housing feature such as a pool, a fireplace, etc.) was to impute missing values as "No X".

The fourteen feature variables with pseudo-missingness were: Alley, BsmtCond, BsmtQual, BsmtFinType1, Fence, Fireplace, GarageCond, GarageFinish, GarageQual, GarageType, GarageYrBlt, MasVnrType, MiscFeature, and PoolQC.

#### True-Missing Values
# #### Actual Missing
# 
# - Electrical --> 'Mode'
# - MasVnrArea --> 'Mode' (group by Neighborhood & Year Built)
# - LotFrontage --> Impute with KNN based on LotConfig, LotShape, and LotArea (Both LotFrontage and missingness in LotFrontage is not evenly distributed across neighborhoods, so Median imputation is less valid)
# - BsmtExposure --> 'Mode' (thirty-seven rows had no values for this feature *or* any other basement feature; those were imputed to be "No Basement." One row had values for other basement columns but not this one; imputed via Mode (group by Neighborhood & Year Built))
# - BsmtFinType2 --> 'Mode' (see above comment)

#### Categorical Variables
#### Ord Categorical & Numeric Features


### New Feature Variables
#  ###### New Features

#  - Total SF = 1stFlrSF + 2ndFlrSF + TotalBsmtSF
#  - TotalFullBath = BsmtFullBath + FullBath
#  - TotalHalfBath = BsmtHalfBath + HalfBath
#  - IsPool  --- Categorical
#  - IsGarage  --- Categorical

### Dummifying Feature Variables
# #### Categorical Dummify Var
# 
#  - LandContour        object --- 4 values, dummify
#  - Exterior1st        object --- 14 values, **Top5(VinylSd, MetalSd, HdBoard, Wd Sdng, Plywood) or Other.
#  - RoofMatl           object --- Dummify. **CompShg or Other
#  - RoofStyle          object --- Dummify. **Gable, Hip or Other.
#  - MSZoning           object --- Dummify.
#  - Street             object --- Dummify. 2 values
#  - Alley              object --- Dummify. 3 values
#  - HouseStyle         object --- Dummify. 8 values
#  - BldgType           object --- Dummify. 5 values
#  - Condition2         object --- Drop, redundant with Condition1
#  - Condition1         object --- Dummify. **Norm or Other.
#  - Exterior2nd        object --- Drop, redundant with Exterior1, 
#  - LandSlope          object --- Dummify. 3 values
#  - LotConfig          object --- Dummify. 3 values
#  - Utilities          object --- Drop. 1 observation 
#  - LotShape           object --- Dummify. **Reg or IReg
#  - Neighborhood       object --- Dummify.
#  - ExterCond          object --- Dummify.
#  - ExterQual          object --- Dummify.
#  - GarageType         object --- Dummify.
#  - GarageQual         object --- Drop, redundant with GarageCond.
#  - FireplaceQu        object --- Dummify. **FirePlace or No Fireplace
#  - PavedDrive         object --- Dummify.
#  - Functional         object --- Dummify. **Y or N(P will be N)
#  - KitchenQual        object --- Dummify.
#  - PoolQC             object --- Drop. IsPool col is created.
#  - Fence              object --- Dummify.
#  - MiscFeature        object --- Drop. redundant with MiscValue
#  - Electrical         object --- Dummify. **SBrkr or Other
#  - MasVnrType         object --- Dummify.
#  - CentralAir         object --- Dummify.
#  - SaleCondition      object --- Dummify.
#  - HeatingQC          object --- Dummify.
#  - Heating            object --- Dummify. **GasA or Other
#  - BsmtFinType2       object --- Drop.
#  - BsmtFinType1       object --- Dummify.
#  - BsmtExposure       object --- Dummify.
#  - BsmtCond           object --- Dummify.
#  - BsmtQual           object --- Dummify.
#  - Foundation         object --- Dummify. **PConc, CBlock, BrkTil, Other
#  - GarageFinish       object --- Dummify. 
#  - SaleType           object --- Dummify. **WD, New, COD, Other
#  - GarageCond         object --- Dummify.

### Removed Feature Variables
The below is a 
#  - Id               float64 --- Drop
#  - BsmtUnfSF        float64 --- Drop
#  - TotalBsmtSF      float64 --- Drop, re-engineered.
#  - SalePrice        float64 --- Target, Drop
#  - 1stFlrSF         float64 --- Drop, re-engineered.
#  - 2ndFlrSF         float64 --- Drop, re-engineered.
#  - LowQualFinSF     float64 --- Drop, 99% has value 0
#  - GrLivArea        float64 --- Drop, correlated with total SF and rooms above ground
#  - BsmtFullBath     float64 --- Drop, re-engineered.
#  - BsmtHalfBath     float64 --- Drop, re-engineered.
#  - FullBath         float64 --- Drop, re-engineered.
#  - HalfBath         float64 --- Drop, re-engineered.
#  - BedroomAbvGr     float64
#  - KitchenAbvGr     float64
#  - TotRmsAbvGrd     float64
#  - Fireplaces       float64
#  - GarageYrBlt      float64 --- Drop, correlated with YrBuilt
#  - GarageCars       float64 --- Drop, correlated with Area
#  - GarageArea       float64 
#  - WoodDeckSF       float64 
#  - OpenPorchSF      float64 --- dummify 1 for OpenPorch 0 for Not OpenPorch
#  - EnclosedPorch    float64 --- dummify if porch 1, else 0
#  - 3SsnPorch        float64 --- dummify if porch 1, else 0
#  - ScreenPorch      float64 --- dummify if porch 1, else 0
#  - PoolArea         float64 --- Drop, over 99% do not have pools
#  - MiscVal          float64 --- **add 1 and then Log transform 
#  - MoSold           float64 --- dummify
#  - YrSold           float64 --- dummify
#  - BsmtFinSF2       float64 --- Drop
#  - BsmtFinSF1       float64 --- Drop
#  - IsPool           float64 --- Categorical
#  - MSSubClass       float64 --- Categorical - convert back to Str
#  - LotFrontage      float64
#  - MasVnrArea       float64
#  - OverallQual      float64 --- dummify
#  - LotArea          float64 --- **add 1 and then Log transform 
#  - OverallCond      float64 --- dummify
#  - YearBuilt        float64
#  - YearRemodAdd     float64